### ISSUE TITLE
Upgrade to cUrl 7.41.0?

### ISSUE THREAD

**Issue by Jan-E** [winlibs/cURL#1]
@weltling Hi Anatol,

Did you already try to update to cUrl 7.41.0? I was experiening build eroors:
http://curl.haxx.se/mail/lib-2015-02/0197.html
http://curl.haxx.se/mail/lib-2015-02/0223.html

Jan

**Comment by weltling** [comment]
@Jan-E @pierrejoye

Hi Jan,

didn't try that yet. Just looked into it and seems it can bypassed, no known security issues in 7.40 and no critical features/fixes in 7.41.

Anatol
