### ISSUE TITLE
curl release 7.88.1. Next: 8.0.0

### ISSUE THREAD

**Issue by Jan-E** [winlibs/cURL#17]
In curl's release calendar version 7.88.1 is announced for Monday 20/02/2023 CET.
Description: this is the last release before 8.0.0. No feature window following this.

**Comment by Jan-E** [comment]
According to the current schedule curl 8.0.0 will be release on 20th March

> curl release 8.0.0
> Monday, 20 March⋅08:00 – 08:30
> Every 8 weeks on Monday, until 14 May 2023

**Comment by Jan-E** [comment]
@cmb69 Is there a reason why you did not update to 7.88.x yet? See a report by someone who is reporting problems with 7.88.1:

https://www.apachelounge.com/viewtopic.php?p=41730#41730

**Comment by ndossche** [comment]
Next release will ship 8.6.0
