### ISSUE TITLE
Fix build when upgrading to cURL 7.49.0

### ISSUE THREAD

**Issue by Jan-E** [winlibs/cURL#2]
@weltling See this PR:
https://github.com/curl/curl/pull/818

**Comment by weltling** [comment]
@Jan-E Thanks. Seems it's not applicable now with 7.49.1, and anyway OpenSSL is used.

Thanks.

**Comment by Jan-E** [comment]
> Seems it's not applicable now with 7.49.1

No. that is because the PR was merged

> and anyway OpenSSL is used.

Without the merge, it would have gone wrong with the standard PHP nmake config options.

Thanks for the ping on cURL 7.49.1 ;-)

**Comment by weltling** [comment]
Yeah, now all good with 7.49.1.

Thanks.
