### ISSUE TITLE
libcurl tags question

### ISSUE THREAD

**Issue by toast12** [winlibs/cURL#3]
I recently downloaded tag curl-7_50_2 and noticed that in this and all previous tags, curlver.h has this line:
# define LIBCURL_VERSION "7.50.2-DEV"

This is not the case in release tarballs. Can you please suggest?

**Comment by toast12** [comment]
To clarify, I want to know why the -DEV part?

**Comment by weltling** [comment]
Hmm, we've never provided libcurl-7.50.2, so not sure what to say. Usually we only provide the versions we use for PHP, that means not every libcurl release might be used. Also usually we use vanilla versions, except there's an explicit bugfix needed. I guess you want to ask this in the upstream repository therefore.

Thanks.
