### ISSUE TITLE
curl 7.53.1 has string 7.53.1-DEV

### ISSUE THREAD

**Issue by toast12** [winlibs/cURL#6]
Hi,

I built the latest version of curl using tag curl-7.53.1. After the build, when here is what it shows:

curl 7.53.1-DEV (x86_64-unknown-linux-gnu) libcurl/7.53.1-DEV OpenSSL/1.0.2k zlib/1.2.7
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy 

The string 7.53..1-DEV has us concerned. Can you please confirm that this is not a dev version?

**Comment by Jan-E** [comment]
Where did you download the sources? Not here:
https://github.com/winlibs/cURL/blob/master/include/curl/curlver.h#L33

And not at the official curl repo:
https://github.com/curl/curl/blob/master/include/curl/curlver.h#L33

Neither at curl.haxx.se
https://curl.haxx.se/download.html
where the downloads contain 7.53.1 without the dev.

**Comment by toast12** [comment]
We downloaded it from git://github.com/bagder/curl.git

Do you maintain that as well?

**Comment by weltling** [comment]
The URL you posted is the upstream project. This repo belongs to the PHP on Windows dedicated lib collection, but might be useful otherwise. Otherwise, upstream issues should be reported upstream.

Thanks.
