### ISSUE TITLE
Curl 7.57.0

### ISSUE THREAD

**Issue by Jan-E** [winlibs/cURL#7]
Curl 7.57.0 has some security fixes that might be applicable to PHP as well:
https://curl.haxx.se/docs/security.html

See for instance the 'SSL out of buffer access' description (for 32-bit systems).

**Comment by weltling** [comment]
Thanks for the ping, @Jan-E. I was right checking them, too ;) I had some issues with 7.56.1, lets see how it goes, but plan to put an update into staging anytime soon anyway.

Thanks.

**Comment by Jan-E** [comment]
I am already recompiling 7.0, 7.1 and 7.2 ATM

**Comment by weltling** [comment]
@Jan-E still have issues with 7.57.0, 13 test fails :/

**Comment by Jan-E** [comment]
Looks like CURLOPT_URL 'file://' is broken. This does not copy the contents from $log_file to $test_file:
```
$testfile_fp = fopen($test_file, 'w+');

$ch = curl_init();
curl_setopt($ch, CURLOPT_FILE, $testfile_fp);
curl_setopt($ch, CURLOPT_URL, 'file://' . $log_file);
curl_exec($ch);
curl_close($ch);
```
This is part of curl_write_file.phpt.

All of the failing tests try to wirite something to a file:// URL.

**Comment by weltling** [comment]
@Jan-E Yeah, that's the exact thing. There was a PR to upstream around 7.52.0 which fixed it, but in the meantime, at least with 7.56.1, it is broken again. In the end i think it is better to patch PHP to handle this, but it won't get into security only branches anyway.

Please use staging or 7.56.0 branch with CVE patches for now, i'll go to fix it in PHP soon.

Thanks.

**Comment by Jan-E** [comment]
@weltling I really do not like using old curl versions. Could we give it a try to fix it upstream once again? See https://github.com/curl/curl/issues/1187#issuecomment-348176804

However, I do not have the knowledge to pinpoint where it goes wrong. So you'll have to do the work.

**Comment by weltling** [comment]
Debian stable still uses 7.52 AFAIR, just for instance. Fine for stable versions. From teh CURL mainstream perspective, it seems that the breach was not intentional, still if happened once could happen again :/ Also latest versions come with multi ssl feature so winssl is enabled automatically and additionally there's smb enabled automatically. More new features are announced. Sounds really too much for a security only version. I'd be going for another round for upstream, if the patch method doesn't work anymore. Otherwise seems ok.

Thanks.

**Comment by Jan-E** [comment]
As far as I can see, this commit fixes the issue:
https://github.com/Jan-E/curl/commit/71692cc683c6c0fa75c2217e0e031e3ff7e642f4

Inserted code:
```
#if defined(WIN32)
    /* Extra handling URLs with an authority component (i.e. that start with
     * "file://")
     */
    /* If the file: path starts with 2 slashes, ditch the slashes */
    if(url_has_scheme && path[0] == '/' && path[1] == '/' && path[2] != '/') {
      /* swallow the two slashes */
      char *ptr = &path[2];
      /* This cannot be done with strcpy, as the memory chunks overlap! */
      memmove(path, ptr, strlen(ptr) + 1);
    }
#endif
```
Using curl.exe shows that besides file:/C: and file:///C: it also accepts file://C:
```
C:\>curl file:/C:\php-sdk\php56dev\Release\php-5.6.32\php.ini
[PHP]
extension_dir = "ext"
extension=php_curl.dll

C:\>curl file://C:\php-sdk\php56dev\Release\php-5.6.32\php.ini
[PHP]
extension_dir = "ext"
extension=php_curl.dll

C:\>curl file:///C:\php-sdk\php56dev\Release\php-5.6.32\php.ini
[PHP]
extension_dir = "ext"
extension=php_curl.dll
```
There is one extra test failing in PHP 5.6.23 nts: the one that checks the protocols, because SMB and SMBS are added.

```
=====================================================================
Number of tests :  100                92
Tests skipped   :    8 (  8.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    4 (  4.0%) (  4.3%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :   88 ( 88.0%) ( 95.7%)
---------------------------------------------------------------------
Time taken      :  117 seconds
=====================================================================

=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
Bug #48203 (Crash when CURLOPT_STDERR is set to regular file) [C:\php-sdk\php56dev\ext\curl\tests\bug48203.phpt]
Variation of bug #48203 with curl_multi_exec (Crash when file pointers passed to curl are c
losed before calling curl_multi_exec) [C:\php-sdk\php56dev\ext\curl\tests\bug48203_multi.phpt]
Bug #54798 (Segfault when CURLOPT_STDERR file pointer is closed before calling curl_exec) [
C:\php-sdk\php56dev\ext\curl\tests\bug54798.phpt]
Check libcurl config on windows [C:\php-sdk\php56dev\ext\curl\tests\check_win_config.phpt]
=====================================================================
```

**Comment by Jan-E** [comment]
@weltling Results for PHP 7.2.0 nts x64:
```
=====================================================================
Number of tests :  110               100
Tests skipped   :   10 (  9.1%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    1 (  0.9%) (  1.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :   99 ( 90.0%) ( 99.0%)
---------------------------------------------------------------------
Time taken      :  106 seconds
=====================================================================

=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
Check libcurl config on windows [N:\php-sdk\php72dev\ext\curl\tests\check_win_config.phpt]
=====================================================================
```

**Comment by weltling** [comment]
@Jan-E nice, so you can go for a PR to the upstream, likely you'll get the best feedback there :) For the patch - no need for strlen() as the the length of `file://` is known. I've a patch for php almost, but no upgrade till next year planned.

Thanks.

**Comment by Jan-E** [comment]
I was not happy about the fix, because it broke file://localhost/.
After a little more testing I fould out that curl accepts
`file://c:/some/path/curl.out`
but rejects
`file://c:\some\path\curl.out`
wih this error message:

> curl: (3) Invalid file://hostname/, expected localhost or 127.0.0.1 or none

See https://github.com/curl/curl/pull/2110#issuecomment-346821200 for the accepted URL's. In the end the fix for file://c:\some\path\curl.out was plain simple: check for a backslash in addition to checking for a forward slash:
https://github.com/curl/curl/commit/b261c44e8c47508ec615b07ad0a27905c8fa15e6

I will go for a PR later today.

**Comment by Jan-E** [comment]
PR https://github.com/curl/curl/pull/2154

**Comment by Jan-E** [comment]
@weltling PR merged. In due time you can upgrade to curl 7.57+

**Comment by weltling** [comment]
@Jan-E thanks for the ping! The deps for the upcoming RCs are already already fixated, will be checking the next relevant curl version which likely to include your patch.

thanks.
