### ISSUE TITLE
Curl buffer tuning Windows

### ISSUE THREAD

**Issue by Jan-E** [winlibs/cURL#9]
@weltling This commit is worthy of porting to the winlibs builds of Curl:
https://github.com/curl/curl/commit/1ba1dba76a8898d1de4dfbc9f1910a352d8a9dab

**Comment by weltling** [comment]
Thanks for the ping, @Jan-E. The config files are now fixed in the core for 7.1+, latest libcurl builds are in the master staging deps yet. Next RCs should have the latest libcurl.

Thanks.
